export const properties = [
  {
    id: 1,
    imageUrl: "/assets/lifeplusplus.gif",
    title: "Life++",
    stack: ["Java", "JavaFX", "Arduino"],
    urlid: "lifepp",
    url: "https://github.com/AlvaroFarreny/Life-plus-plus",
    description:
      "Desktop app that manages different types of users through a database, stores information on future patients thanks to a bracelet with a pulse oximeter and GPS, and allows future doctors to monitor said data in real time",
  },
  {
    id: 2,
    imageUrl: "/assets/movierecommender.jpg",
    title: "Movie Recommender",
    stack: ["Python", "Tkinter"],
    urlid: "movierecommender",
    url: "https://github.com/AlvaroFarreny/SSII-Movielens",
    description:
      "Movie recommender to users and given reviews of other movies based on MovieLens database.",
  },
  {
    id: 3,
    imageUrl: "/assets/criptoclub.png",
    title: "CriptoClub Website",
    urlid: "criptoclub",
    stack: ["HTML+CSS", "JavaScript", "PHP"],
    url: "https://github.com/AlvaroFarreny/WebFinalProject",
    description:
      "The final project for the subject of Web&App Development based on making the website for the Cryptoclub of the Universidad Europea de Madrid",
  },
  {
    id: 4,
    imageUrl: "/assets/btc_analisis.jpg",
    title: "BTC Sentiment Analysis Algortihm",
    urlid: "btcanalisis",
    stack: ["Python"],
    url: "https://github.com/AlvaroFarreny/AnalisisSentimientosBTC",
    description:
      "Artificial Intelligence project based on the analysis of BTC sentiment on twitter to try to predict the price based on tweets.",
  },
  {
    id: 6,
    imageUrl: "/assets/covidApp.png",
    title: "CovidApp",
    urlid: "covidapp",
    stack: ["Python", "Django"],
    url: "https://github.com/AlvaroFarreny/CovidAPP",
    description:
      "Application made in Python and Django to read COVID passports through QR and give a quick verification instantly.",
  },
  {
    id: 7,
    imageUrl: "/assets/biteabit.png",
    title: "Bite a Bit",
    urlid: "biteabit",
    stack: ["Python"],
    url: "https://github.com/AlvaroFarreny/CovidAPP",
    description: ".",
  },
  {
    id: 8,
    imageUrl: "/assets/fitfoods.png",
    title: "FitFoods",
    urlid: "fitfoods",
    stack: ["React", "Laravel", "MySQL"],
    url: "https://github.com/AlvaroFarreny/fitfoods",
    description: ".",
  },
  {
    id: 9,
    imageUrl: "/assets/camaronft.jpg",
    title: "CamaroNFT",
    urlid: "nombrescamaro",
    stack: ["Python"],
    url: "https://github.com/AlvaroFarreny/CovidAPP",
    description: ".",
  },
  {
    id: 10,
    imageUrl: "/assets/balucover.png",
    title: "BaluApp",
    urlid: "balu",
    stack: ["React Native"],
    url: "https://github.com/AlvaroFarreny/CovidAPP",
    description: ".",
  },
  {
    id: 11,
    imageUrl: "/assets/dabz.png",
    title: "Dabz",
    urlid: "https://dabz.es/",
    stack: ["WordPress"],
    url: "https://github.com/AlvaroFarreny/CovidAPP",
    description: ".",
  },
];
